baseURL = "https://blog.joernahrens.de/"
languageCode = "en-us"
title = "Jörn Ahrens"

theme = "hermit" # Set the theme.
defaultcontentlanguage = "en" # The default content language.

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.

[params] # theme parameters
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  themeColor = "#32a852"

  author = "Jörn Ahrens" # Author's name.
  info = "Android Developer" # Author's job title or info.
  description = "Jörn Ahrens' personal website" # Site description.
  keywords = "blog,developer,personal,android,software" # Site keywords.
  avatarurl = "images/avatar.png" # Contain the path of the optional avatar in the static folder.

  relatedPosts = false  # Add a related content section to all single posts page
    footercontent = "" # Add footer content
    #fixedbarContent = "Do you want to know me more private?→" # Add fixedbar content
    #fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = true  # new add
    enableFacebookShare = true # new add
    enableHatenaShare = false   # new add
    enableLineShare = false     # new add
    enableLinkedInShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "github"
    url = "https://github.com/joernahrens/"
[[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/j%C3%B6rn-ahrens-398a81b0"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "about"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "posts"
[[menu.main]]
    name = "Contact"
    weight = 3
    url = "contact"
